/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design;


/**
 *
 * @author joseph.baert
 */
public class CarLayout extends javax.swing.JPanel {
    
    
    /**
     * Creates new form CarLayout
     */
    public CarLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        card1 = new design.card();
        card2 = new design.card();
        card3 = new design.card();

        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane1.setLayout(new java.awt.GridLayout(1, 0, 25, 0));

        card1.setBackground(new java.awt.Color(51, 0, 153));
        card1.setForeground(new java.awt.Color(0, 0, 102));
        card1.setColor1(new java.awt.Color(0, 51, 204));
        card1.setColor2(new java.awt.Color(0, 0, 153));
        jLayeredPane1.add(card1);

        card2.setColor1(new java.awt.Color(204, 102, 0));
        card2.setColor2(new java.awt.Color(255, 153, 0));
        jLayeredPane1.add(card2);

        card3.setColor1(new java.awt.Color(0, 102, 0));
        jLayeredPane1.add(card3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public design.card card1;
    public design.card card2;
    public design.card card3;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
